#网络架构

![softmax回归是一种单层神经网络](../resource/pytorch/img/softmaxreg.svg)
:label:`fig_softmaxreg`

# softmax回归的从零开始实现

## 导包和数据集构建

In [1]:
import torch
from IPython import display
from d2l import torch as d2l

In [3]:
batch_size = 256
train_iter, test_iter = d2l.load_data_fashion_mnist(batch_size)
for X, y in train_iter:
    break
y.shape

torch.Size([256])

## 初始化模型参数
原始数据集中的每个样本都是$28 \times 28$的图像。
本节**将展平每个图像，把它们看作长度为784的向量作为输入，则输入的形状为(batch_size, 784)**



权重将构成一个$784 \times 10$的矩阵，
偏置将构成一个$1 \times 10$的行向量。

In [1]:
num_input = 784
num_output = 10

W = torch.normal(0, 0.01, size=(num_input, num_output), requires_grad=True)
b = torch.zeros(num_output, requires_grad=True)


NameError: name 'torch' is not defined

## 定义softmax操作

表达式

$$
\mathrm{softmax}(\mathbf{X})_{ij} = \frac{\exp(\mathbf{X}_{ij})}{\sum_k \exp(\mathbf{X}_{ik})}.
$$

[**实现softmax**]由三个步骤组成：

1. 对每个项求幂（使用`exp`）；
1. 对每一行求和（小批量中每个样本是一行），得到每个样本的规范化常数；
1. 将每一行除以其规范化常数，确保结果的和为1。

要注意的是式中的X其实是XW + b的结果，是一个 形状(batch_size, 10)的矩阵，因此每一行都有10个元素(每一行是一个样本)

In [ ]:
def softmax(X):
    X_exp = torch.exp(X)
    line_exp = X_exp.sum(1, keepdims = True)
    return X_exp / line_exp #line_exp的每一行元素都广播成同一元素

## 定义模型

**实现softmax回归模型**

教材上说的展平为向量，实际上是一个二维的(batch_size, 1)列向量

In [12]:
def net(X):
    return softmax(torch.matmul(X.reshape(-1, W.shape[0]), W) + b ) #得把数据集reshape成(batch_size, num_input)形状
    #y_hat shape:[batch_size, num_output]

## 定义损失函数

交叉熵损失函数

$$ l(\mathbf{y}, \hat{\mathbf{y}}) = - \sum_{j=1}^q y_j \log \hat{y}_j. $$

In [13]:
y = torch.tensor([0,2])
y_hat = torch.tensor([[1,2,3,4], [5,6,7,8]])
y_hat[[0, 1], y]

tensor([1, 7])

In [14]:
def cross_entropy(y_hat, y):
    return - torch.log(y_hat[range(len(y_hat)), y]) * y

cross_entropy(y_hat, y)

tensor([-0.0000, -3.8918])

## 分类精度

即正确预测数量与总预测数量之比。

In [15]:
a = torch.randn(4, 4)
print(a.type(dtype=torch.int32))


tensor([[ 0, -1, -1,  0],
        [-2,  0,  0,  0],
        [ 1,  0,  0,  0],
        [ 0,  0,  0,  0]], dtype=torch.int32)


In [16]:
def accuracy(y_hat, y):
    """计算单样本中预测正确的数量"""
    y_hat_argmax = y_hat.argmax(dim=1)
    cmp = y_hat_argmax.type(y.dtype) == y
    return float(cmp.sum())   #要用float把tensor形式转化为python的float形式

In [17]:
y = torch.tensor([0, 2])
y_hat = torch.tensor([[0.1, 0.3, 0.6], [0.3, 0.2, 0.5]])
print(accuracy(y_hat, y) / len(y))

0.5


定义一个实用程序类`Accumulator`，用于创建列表来储存各种信息并累加值

在(**`Accumulator`实例中创建了2个变量，
分别用于存储正确预测的数量和预测的总数量**)。
当我们遍历数据集时，两者都将随着时间的推移而累加。

In [18]:
class Accumulator:
    def __init__(self, n):
        self.data = [0.0] * n            
    
    def add(self, *args):
        self.data = [a + float(b) for a,b in zip(self.data, args)]  #关键：zip配对
        
    def __getitem__(self, idx):
        self.data[idx] = self[idx]

In [19]:
acc = Accumulator(2)
acc.add(2.0,3.0)

创建一个通用函数，对于任意数据迭代器`data_iter`可访问的数据集，可用于评估在任意模型`net`的精度

用到上面创建的Accumulator类

In [20]:
def evaluate_accuracy(net, test_iter):
    """计算在指定数据集上模型的精度"""
    # 将模型设置为评估模式
    if isinstance(net, torch.nn.Module):
        net.eval()
    # Accumulator类储存正确预测数、预测总数
    accum = Accumulator(2)
    # 累加所有数据集的正确预测数、预测总数
    with torch.no_grad():   #因为调用了神经网络实例net，所以禁用梯度计算
        for X, y in test_iter:
            accum.add(accuracy(net(X), y), y.numel()) #不能用len(y)
    
    return accum[0] / accum[1]

## 训练


In [21]:
def train_epoch_ch3(net, train_iter, loss, updater):
    """训练模型一个迭代周期"""
    # 将模型设置为训练模式
    if isinstance(net, torch.nn.Module):
        net.train()
    # 增加变量用于储存训练损失总和、训练准确的样本总和、样本数
    matric = Accumulator(3)
    # 训练
    for X, y in train_iter:
        #loss
        y_hat = net(X)
        Loss = loss(y_hat, y)
        #梯度下降   
        if isinstance(updater, torch.optim.Optimizer):
            # 使用PyTorch内置的优化器和损失函数
            updater.zero_grad
            updater.mean().backward()   #先取均值再反向传播
            updater.step
            
        else:
            # 使用定制的优化器和损失函数
            Loss.sum().backward()
            updater(batch_size)

        matric.add(Loss.sum(), accuracy(y_hat, y), y.numel())        

    # 返回累加后的训练损失和训练精度
    return matric[0], matric[1] / matric[2]

[**定义一个在动画中绘制数据的实用程序类**]`Animator`

直接抄了

In [22]:
class Animator:  #@save
    """在动画中绘制数据"""
    def __init__(self, xlabel=None, ylabel=None, legend=None, xlim=None,
                 ylim=None, xscale='linear', yscale='linear',
                 fmts=('-', 'm--', 'g-.', 'r:'), nrows=1, ncols=1,
                 figsize=(3.5, 2.5)):
        # 增量地绘制多条线
        if legend is None:
            legend = []
        d2l.use_svg_display()
        self.fig, self.axes = d2l.plt.subplots(nrows, ncols, figsize=figsize)
        if nrows * ncols == 1:
            self.axes = [self.axes, ]
        # 使用lambda函数捕获参数
        self.config_axes = lambda: d2l.set_axes(
            self.axes[0], xlabel, ylabel, xlim, ylim, xscale, yscale, legend)
        self.X, self.Y, self.fmts = None, None, fmts

    def add(self, x, y):
        # 向图表中添加多个数据点
        if not hasattr(y, "__len__"):
            y = [y]
        n = len(y)
        if not hasattr(x, "__len__"):
            x = [x] * n
        if not self.X:
            self.X = [[] for _ in range(n)]
        if not self.Y:
            self.Y = [[] for _ in range(n)]
        for i, (a, b) in enumerate(zip(x, y)):
            if a is not None and b is not None:
                self.X[i].append(a)
                self.Y[i].append(b)
        self.axes[0].cla()
        for x, y, fmt in zip(self.X, self.Y, self.fmts):
            self.axes[0].plot(x, y, fmt)
        self.config_axes()
        display.display(self.fig)
        display.clear_output(wait=True)

实现一个[**训练函数**]，
它会在`train_iter`访问到的训练数据集上训练一个模型`net`。
该训练函数将会运行多个迭代周期（由`num_epochs`指定）。
在每个迭代周期结束时，利用`test_iter`访问到的测试数据集对模型进行评估。
我们将利用`Animator`类来可视化训练进度。

In [23]:
def train_ch3(net, train_iter, test_iter, loss, num_epochs, updater):
    #抄可视化
    animator = Animator(xlabel='epoch', xlim=[1, num_epochs], ylim=[0.3, 0.9],
                        legend=['train loss', 'train acc', 'test acc'])
    
    # 训练
    for epoch in range(num_epochs):
        matric = train_epoch_ch3(net, train_iter, loss, updater)
        test_acc = evaluate_accuracy(net, test_iter)
        # animator.add
        animator.add(epoch + 1, matric)
    loss_sum, train_acc = matric


使用 :numref:`sec_linear_scratch`中定义的
[**小批量随机梯度下降来优化模型的损失函数**]，设置学习率为0.1。


In [24]:
lr = 0.1

def updater(batch_size):
    return d2l.sgd([W, b], lr, batch_size)

In [ ]:
num_epochs = 10
train_ch3(net, train_iter, test_iter, cross_entropy, num_epochs, updater)

In [ ]:
loss = torch.randn(10)
print(loss.shape,loss.sum())


torch.Size([10]) tensor(-0.7701)
